# Generated by Django 4.2.20 on 2025-05-11 20:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0002_alter_profile_email'),
        ('merchstore', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('status', models.CharField(choices=[('on_cart', 'On Cart'), ('to_pay', 'To Pay'), ('to_ship', 'To Ship'), ('to_receive', 'To Receive'), ('delivered', 'Delivered')], default='on_cart', max_length=20)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('buyer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transaction', to='user_management.profile')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transaction', to='merchstore.product')),
            ],
        ),
    ]
