# Generated by Django 4.2.19 on 2025-03-08 05:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('merchstore', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='producType',
            new_name='productType',
        ),
    ]
