# Generated by Django 4.2.19 on 2025-03-08 06:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('merchstore', '0002_rename_productype_product_producttype'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='producttype',
            options={'ordering': ['name'], 'verbose_name_plural': 'Product Types'},
        ),
    ]
