# Generated by Django 4.2.20 on 2025-05-14 18:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchstore', '0002_transaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('available', 'Available'), ('on sale', 'On Sale'), ('out of stock', 'Out of Stock')], default='available', max_length=20),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='amount',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='status',
            field=models.CharField(choices=[('on cart', 'On Cart'), ('to pay', 'To Pay'), ('to ship', 'To Ship'), ('to receive', 'To Receive'), ('delivered', 'Delivered')], default='on cart', max_length=20),
        ),
    ]
