# Generated by Django 4.2.20 on 2025-05-14 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchstore', '0002_transaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='status',
            field=models.CharField(choices=[('on cart', 'On Cart'), ('to pay', 'To Pay'), ('to ship', 'To Ship'), ('to receive', 'To Receive'), ('delivered', 'Delivered')], default='on cart', max_length=20),
        ),
    ]
