# Generated by Django 4.2.20 on 2025-06-06 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('merchstore', '0003_alter_product_status_alter_transaction_amount_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='amount',
            new_name='quantity',
        ),
    ]
