# Generated by Django 4.2.19 on 2025-03-08 09:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('merchstore', '0003_alter_producttype_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='productType',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product', to='merchstore.producttype'),
        ),
    ]
