# Generated by Django 4.2.19 on 2025-03-09 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('merchstore', '0004_alter_product_producttype'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='productType',
            new_name='product_type',
        ),
    ]
