# Generated by Django 4.2.19 on 2025-03-08 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commissions', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='commission',
            old_name='peopleRequired',
            new_name='people_required',
        ),
    ]
