# Generated by Django 4.2.19 on 2025-03-09 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commissions', '0002_rename_peoplerequired_commission_people_required'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='updated_on',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='commission',
            name='updated_on',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
