# Generated by Django 4.2.20 on 2025-05-04 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commissions', '0003_alter_comment_updated_on_alter_commission_updated_on'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commission',
            name='people_required',
        ),
        migrations.AddField(
            model_name='commission',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('full', 'Full'), ('completed', 'Completed'), ('discontinued', 'Discontinued')], default='open', max_length=20),
        ),
    ]
