# Generated by Django 4.2.20 on 2025-05-10 23:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commissions', '0004_remove_commission_people_required_commission_status'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
